language: minimal
dist: trusty

before_install:
  - docker login -u="${RH_REGISTRY_USER}" -p="${RH_REGISTRY_PASS}" registry.redhat.io
  - docker login -u="${DOCKER_REGISTRY_USER}" -p="${DOCKER_REGISTRY_PASS}"

script:
  - docker build -t "s1061123/multus-ci-scripts:latest" .

deploy:
  provider: script
  on:
    branch: master
  script: >
    bash -c '
    docker push "s1061123/multus-ci-scripts:latest";
    echo done'
